hover_point:
    height: 1.0

tracking:
    min_track_time: 5.0
    target_lost_limit: 1.0
    position_offset:
        x: 0.0
        y: 0.0
        z: 0.0

landing:
    height_update:
        period: 2
        threshold:
            x: 2.1
            y: 2.2
        multiplier:
            descend: 0.7
            recover: 1.2

    disarm_conditions:
        # x, y ,z disarm conditions from AprilTag center
        x_cutoff: 0.5
        y_cutoff: 0.5
        z_cutoff: 0.2

        # num of frames apriltag is detected before disarm
        # this introduces noise rejection
        belief_threshold: 10
