camera_type: "firefly"
camera_index: 0
camera_imshow: 1
camera_snapshot: 1
apriltag_imshow: 1

nb_configs: 3
config_keys:
    ["default", "340", "160"]
config_files:
    [
        "ost_640.yaml",
        "ost_320.yaml",
        "ost_160.yaml"
    ]
