camera_type: "firefly"
camera_index: 0
camera_imshow: 1
camera_snapshot: 1
apriltag_imshow: 1

nb_configs: 3
config_keys:
    ["320", "160", "640"]
config_files:
    [
        "320_by_240.yaml",
        "160_by_120.yaml",
        "640_by_480.yaml"
    ]
