roll_controller:
  min: -30.0
  max: 30.0
  k_p: 0.1
  k_i: 0.0
  k_d: 0.01

pitch_controller:
  min: -30.0
  max: 30.0
  k_p: 0.1
  k_i: 0.0
  k_d: 0.01

vz_controller:
  hover_throttle: 0.5
  descent_velocity: -0.3
  k_p: 0.1
  k_i: 0.0
  k_d: 0.01
