at_controller:
  min: -20.0
  max: 20.0
  k_p: 0.1
  k_i: 0.0
  k_d: 0.01

ct_controller:
  min: -20.0
  max: 20.0
  k_p: 0.2
  k_i: 0.0
  k_d: 0.15

z_controller:
  hover_throttle: 0.5
  k_p: 0.2
  k_i: 0.0
  k_d: 0.1
