at_controller:
  min: -35.0
  max: 35.0
  k_p: 0.3
  k_i: 0.0
  k_d: 0.08

ct_controller:
  min: -30.0
  max: 30.0
  k_p: 0.08
  k_i: 0.0
  k_d: 0.04

z_controller:
  hover_throttle: 0.4
  k_p: 0.2
  k_i: 0.0
  k_d: 0.1
