dist: trusty
sudo: required

language:
  - python
  - c++
  
cache:
  - apt

virtualenv:
  system_site_packages: true

before_install:
  - bash scripts/ros_install.bash
  - bash scripts/hector_quad_simulator.bash

notifications:
    recipients:
        - stan.j.brown@gmail.com
        - chutsu@gmail.com 
    email:
        on_success: change
        on_failure: always
