dist: trusty
sudo: required

language:
  - c++

cache:
  - apt

before_install:
  - sudo sh scripts/ros_install.sh
  - sudo sh scripts/hector_quad_simulator_install.sh

notifications:
    recipients:
        - stan.j.brown@gmail.com
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
