dist: trusty
sudo: required

language:
    - c++

cache:
    - apt

install:
    - sudo bash scripts/install/ros_install.bash
    - sudo bash scripts/install/install_deps.bash

script:
    - echo "Skipping tests for now!"
    # - cd ~/catkin_ws/src/awesomo/awesomo_core
    # - source ~/catkin_ws/devel/setup.bash
    # - rosrun awesomo_core awesomo_tests --gtest_filter=-Camera.*:SBGC.* --silence-stdcout

notifications:
    recipients:
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
