dist: trusty
sudo: required

language:
    - c++

cache:
    - apt

before_install:
    - sudo bash scripts/install_scripts/ros_install.bash
    - sudo bash scripts/install_scripts/apriltag_install.bash

script:
    - make

notifications:
    recipients:
        - chutsu@gmail.com
        - stan.j.brown@gmail.com
    email:
        on_success: change
        on_failure: always
