dist: trusty
sudo: required

language:
    - c++

cache:
    - apt

install:
    - sudo bash scripts/install/ros_install.bash
    - sudo bash scripts/install/catkin_setup.bash
    - sudo bash scripts/install/awesomo_install.bash

script:
    - cd ~/catkin_ws/src/awesomo/awesomo_core
    - rosrun awesomo_core awesomo_tests

notifications:
    recipients:
        - chutsu@gmail.com
        - stan.j.brown@gmail.com
    email:
        on_success: change
        on_failure: always
