dist: trusty
sudo: required

language:
  - c++

cache:
  - apt

before_install:
  - sudo bash scripts/ros_install.bash
  - sudo bash scripts/hector_quad_simulator_install.bash
  
script:
  - echo "Done :)"

notifications:
    recipients:
        - stan.j.brown@gmail.com
    email:
        on_success: change
        on_failure: always
