dist: trusty
sudo: required

language:
    - c++

cache:
    - apt

install:
    - sudo bash scripts/install_scripts/ros_install.bash
    - sudo bash scripts/install_scripts/catkin_setup.bash
    - cd ~/catkin_ws/src/
    - git clone https://github.com/wavelab/awesomo.git
    - cd ~/catkin_ws/ && catkin_make

script:
    - cd ~/catkin_ws/src/awesomo_core
    - rosrun awesomo_core awesomo_tests

notifications:
    recipients:
        - chutsu@gmail.com
        - stan.j.brown@gmail.com
    email:
        on_success: change
        on_failure: always
