camera_type: "ximea"
camera_index: 0
camera_imshow: 1
camera_snapshot: 0
camera_exposure_value: 10000  # usecs
camera_gain_value: 12.0  # 0 - 16 (DO NOT USE 16; crashes ximea)
apriltag_imshow: 0

nb_configs: 2
config_keys: ["320", "160"]
config_dists: [2.0]
config_files: ["320_by_240.yaml", "160_by_120.yaml"]

nb_apriltags: 2
apriltag_ids: [0, 5]
apriltag_sizes: [0.048, 0.343]
# apriltag_sizes: [0.07, 0.6]
