camera_type: "firefly"
camera_index: 0
camera_imshow: 0
camera_snapshot: 0
camera_exposure_value: 1
camera_gain_value: 15.0  # between 0 - 24.0
apriltag_imshow: 0

nb_configs: 2
config_keys: ["640", "320"]
config_dists: [1.0]
config_files: ["320_by_240.yaml", "320_by_240.yaml"]

nb_apriltags: 2
apriltag_ids: [0, 5]
# apriltag_sizes: [0.048, 0.343]
apriltag_sizes: [0.07, 0.6]
# apriltag_sizes: [0.161, 0.161]
