roll_controller:
    min: -30
    max: 30
    k_p: 12.0
    k_i: 0.05
    k_d: 1.15

pitch_controller:
    min: -30
    max: 30
    k_p: 12.0
    k_i: 0.05
    k_d: 1.15

throttle_controller:
    hover_throttle: 0.5
    k_p: 1.0
    k_i: 0.0
    k_d: 0.5

landing:
    height_update:
        period: 0.3
        multiplier:
            descend: 0.8
            recover: 1.2

    disarm_conditions:
        # x, y ,z disarm conditions from AprilTag center
        x_cutoff: 0.15
        y_cutoff: 0.15
        z_cutoff: 0.15

        # num of frames apriltag is detected before disarm
        # this introduces redundancy rejection
        belief_threshold: 200
