roll_controller:
    k_p: 0.3
    k_i: 0.0
    k_d: 0.2

pitch_controller:
    k_p: 0.3
    k_i: 0.0
    k_d: 0.2

throttle_controller:
    hover_throttle: 0.5
    k_p: 0.4
    k_i: 0.0
    k_d: 0.2

vx_controller:
    k_p: 0.1
    k_i: 0.0
    k_d: 0.0
vy_controller:
    k_p: 0.1
    k_i: 0.0
    k_d: 0.0
vz_controller:
    k_p: 0.2
    k_i: 0.0
    k_d: 0.0

roll_limit:
    min: -30.0
    max: 30.0

pitch_limit:
    min: -30.0
    max: 30.0

throttle_limit:
    min: -1.0
    max: 1.0

trajectory_index: "trajectory/index.csv"

blackbox_enable: true
blackbox_rate: 0.2
blackbox_file: "/tmp/landing_blackbox.csv"
