roll_controller:
    min: -30
    max: 30
    k_p: 0.3
    k_i: 0.0
    k_d: 0.2

pitch_controller:
    min: -30
    max: 30
    k_p: 0.3
    k_i: 0.0
    k_d: 0.2

throttle_controller:
    hover_throttle: 0.5
    k_p: 0.4
    k_i: 0.0
    k_d: 0.2
