roll_controller:
    min: -30
    max: 30
    k_p: 0.9
    k_i: 0.01
    k_d: 0.33

pitch_controller:
    min: -30
    max: 30
    k_p: 0.9
    k_i: 0.01
    k_d: 0.33

throttle_controller:
    hover_throttle: 0.5
    k_p: 3.0
    k_i: 0.0
    k_d: 0.5
