roll_controller:
    min: -30
    max: 30
    k_p: 12.0
    k_i: 0.05
    k_d: 1.15

pitch_controller:
    min: -30
    max: 30
    k_p: 12.0
    k_i: 0.05
    k_d: 1.15

throttle_controller:
    hover_throttle: 0.5
    k_p: 1.0
    k_i: 0.0
    k_d: 0.5
