vx_controller:
    pitch_min: -30
    pitch_max: 30
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
vy_controller:
    roll_min: -30
    roll_max: 30
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
vz_controller:
    throttle_min: -1.0
    throttle_max: 1.0
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
