vx_controller:
    pitch_min: -30.0
    pitch_max: 30.0
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
vy_controller:
    roll_min: -30.0
    roll_max: 30.0
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
vz_controller:
    hover_throttle: 0.6
    k_p: 0.1
    k_i: 0.0
    k_d: 0.01
