roll_controller:
    setpoint: 0.0
    deadzone: 0.01
    min: -0.25
    max: 0.25
    k_p: 0.25
    k_i: 0.01
    k_d: 0.2
pitch_controller:
    setpoint: 0.0
    deadzone: 0.01
    min: -0.25
    max: 0.25
    k_p: 0.25
    k_i: 0.01
    k_d: 0.2
throttle_controller:
    hover_throttle: 0.5
    setpoint: 0.0
    deadzone: 0.0
    min: -0.4
    max: 0.4
    k_p: 0.1
    k_i: 0.0
    k_d: 0.05
