roll_controller:
    setpoint: 0.0
    deadzone: 0.1
    min: -0.2
    max: 0.2
    k_p: 0.205
    k_i: 0.05
    k_d: 20
pitch_controller:
    setpoint: 0.0
    deadzone: 0.1
    min: -0.2
    max: 0.2
    k_p: 0.205
    k_i: 0.05
    k_d: 20
throttle_controller:
    setpoint: 1.0
    deadzone: 0.0
    min: -0.1
    max: 0.1
    k_p: 0.13
    k_i: 0.0
    k_d: 2
