roll_controller:
    setpoint: 0.0
    deadzone: 0.1
    min: -0.2
    max: 0.2
    k_p: 0.205
    k_i: 0.02
    k_d: 6
pitch_controller:
    setpoint: 0.0
    deadzone: 0.1
    min: -0.2
    max: 0.2
    k_p: 0.205
    k_i: 0.02
    k_d: 6
throttle_controller:
    setpoint: 1.0
    deadzone: 0.0
    min: -0.1
    max: 0.1
    k_p: 0.12
    k_i: 0.0
    k_d: 2
