tag_family: "Tag16h5"
tag_sanity_check: 30  # euclidean distance in meters

# normal black and white tag
# tag_ids: [0]
# tag_sizes: [0.951]

# nested illumination invariant tag
tag_ids: [0, 5]
tag_sizes: [0.1, 0.857]

camera_config: "../camera/prototype"
windowing: true
window_padding: 0.3
illum_invar: true
imshow: false
