tag_family: "Tag16h5"

# normal black and white tag
# tag_ids: [0]
# tag_sizes: [0.951]

# nested illumination invariant tag
tag_ids: [0, 5]
tag_sizes: [0.1, 0.857]

camera_config: "../camera/prototype"
# imshow: true
imshow: false
