roll_controller:
    min: -30.0
    max: 30.0
    k_p: 0.1
    k_i: 0.0
    k_d: 0.0

pitch_controller:
    min: -30.0
    max: 30.0
    k_p: 0.1
    k_i: 0.0
    k_d: 0.0

throttle_controller:
    hover_throttle: 0.40
    k_p: 0.35
    k_i: 0.0
    k_d: 0.1
