roll_controller:
    min: -25.0
    max: 25.0
    k_p: 0.08
    k_i: 0.0
    k_d: 0.04

pitch_controller:
    min: -25.0
    max: 25.0
    k_p: 0.08
    k_i: 0.0
    k_d: 0.04

throttle_controller:
    hover_throttle: 0.40
    k_p: 0.1
    k_i: 0.0
    k_d: 0.05
