roll_controller:
    k_p: 0.1
    k_i: 0.003
    k_d: 0.04

pitch_controller:
    k_p: 0.1
    k_i: 0.003
    k_d: 0.04

throttle_controller:
    hover_throttle: 0.5
    k_p: 0.1
    k_i: 0.001
    k_d: 0.05

roll_limit:
    min: -30.0
    max: 30.0

pitch_limit:
    min: -30.0
    max: 30.0

track_offset: [0.0, 0.0, 0.0]
