channel_1:
  min: 1072
  max: 1910
---
channel_2:
  min: 1079
  max: 1917
---
channel_3:
  min: 1008
  max: 1918
---
channel_4:
  min: 1090
  max: 1920
---
channel_5:
  min: 961
  max: 2067
---
channel_6:
  min: 960
  max: 2067
