channel_1:
  min: 1494
  max: 1494
---
channel_2:
  min: 1499
  max: 1499
---
channel_3:
  min: 1157
  max: 1157
---
channel_4:
  min: 1509
  max: 1509
---
channel_5:
  min: 961
  max: 961
---
channel_6:
  min: 2067
  max: 2067
