vx_controller:
    k_p: 0.1
    k_i: 0.01
    k_d: 0.0

vy_controller:
    k_p: 0.1
    k_i: 0.01
    k_d: 0.0

vz_controller:
    k_p: 0.1
    k_i: 0.0
    k_d: 0.0

roll_limit:
    min: -60.0
    max: 60.0

pitch_limit:
    min: -60.0
    max: 60.0

throttle_limit:
    min: -1.0
    max: 1.0

trajectory_index: "../../trajectory/index.csv"
trajectory_threshold: [1.0, 1.0, 1.0]

blackbox_enable: true
blackbox_rate: 0.1
blackbox_file: "/tmp/landing_blackbox.csv"
