camera_mount:
    RBT_between_cam_and_FC:
        x: 0.0
        y: 0.0
        z: 0.0
        roll: 0.0
        pitch: -90.0
        yaw: 180.0
    
    gimbal_limits:
        roll_upper_limit: 20.0
        roll_lower_limit: -20.0
        pitch_upper_limit: 30.0
        pitch_lower_limit: -40.0
        yaw_upper_limit: 0.0
        yaw_lower_limit: 0.0
