roll_controller:
  min: -30.0
  max: 30.0
  k_p: 0.48
  k_i: 0.0
  k_d: 0.3

pitch_controller:
  min: -30.0
  max: 30.0
  k_p: 0.4
  k_i: 0.0
  k_d: 0.2

throttle_controller:
  hover_throttle: 0.5
  k_p: 0.35
  k_i: 0.0
  k_d: 0.1

track_offset: [0.0, 0.0, 0.0]
